# Generated by Django 2.2.5 on 2019-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('date_published', models.DateField(blank=True)),
                ('user_profile_link', models.URLField(blank=True)),
            ],
        ),
    ]
